import React, { useState } from 'react';
import { Link } from 'react-router-dom'; // Assuming you're using react-router-dom

export const productData = {
  Telefon: [
    {
      id: 1,
      name: 'Telefon 1',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Telefon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 2,
      name: 'Telefon 2',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Telefon+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 3,
      name: 'Telefon 3',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Telefon+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
    {
      id: 4,
      name: 'Telefon 4',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Telefon+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 5,
      name: 'Telefon 5',
      price: '900 $',
      image: 'https://via.placeholder.com/150?text=Telefon+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (900 / 3).toFixed(2) },
        { months: 6, price: (900 / 6).toFixed(2) },
        { months: 9, price: (900 / 9).toFixed(2) },
        { months: 12, price: (900 / 12).toFixed(2) },
      ],
    },
    {
      id: 6,
      name: 'Telefon 6',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Telefon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 7,
      name: 'Telefon 7',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Telefon+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 8,
      name: 'Telefon 8',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Telefon+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
    {
      id: 9,
      name: 'Telefon 9',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Telefon+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 10,
      name: 'Telefon 10',
      price: '900 $',
      image: 'https://via.placeholder.com/150?text=Telefon+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (900 / 3).toFixed(2) },
        { months: 6, price: (900 / 6).toFixed(2) },
        { months: 9, price: (900 / 9).toFixed(2) },
        { months: 12, price: (900 / 12).toFixed(2) },
      ],
    },
    {
      id: 11,
      name: 'Telefon 11',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Telefon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 12,
      name: 'Telefon 12',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Telefon+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 13,
      name: 'Telefon 13',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Telefon+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
    {
      id: 14,
      name: 'Telefon 14',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Telefon+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 15,
      name: 'Telefon 15',
      price: '900 $',
      image: 'https://via.placeholder.com/150?text=Telefon+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (900 / 3).toFixed(2) },
        { months: 6, price: (900 / 6).toFixed(2) },
        { months: 9, price: (900 / 9).toFixed(2) },
        { months: 12, price: (900 / 12).toFixed(2) },
      ],
    },
  ],
  Bilgisayar: [
    {
      id: 16,
      name: 'Bilgisayar 1',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 17,
      name: 'Bilgisayar 2',
      price: '1200 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1200 / 3).toFixed(2) },
        { months: 6, price: (1200 / 6).toFixed(2) },
        { months: 9, price: (1200 / 9).toFixed(2) },
        { months: 12, price: (1200 / 12).toFixed(2) },
      ],
    },
    {
      id: 18,
      name: 'Bilgisayar 3',
      price: '1400 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1400 / 3).toFixed(2) },
        { months: 6, price: (1400 / 6).toFixed(2) },
        { months: 9, price: (1400 / 9).toFixed(2) },
        { months: 12, price: (1400 / 12).toFixed(2) },
      ],
    },
    {
      id: 19,
      name: 'Bilgisayar 4',
      price: '1600 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1600 / 3).toFixed(2) },
        { months: 6, price: (1600 / 6).toFixed(2) },
        { months: 9, price: (1600 / 9).toFixed(2) },
        { months: 12, price: (1600 / 12).toFixed(2) },
      ],
    },
    {
      id: 20,
      name: 'Bilgisayar 5',
      price: '1800 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1800 / 3).toFixed(2) },
        { months: 6, price: (1800 / 6).toFixed(2) },
        { months: 9, price: (1800 / 9).toFixed(2) },
        { months: 12, price: (1800 / 12).toFixed(2) },
      ],
    },
    {
      id: 21,
      name: 'Bilgisayar 6',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 22,
      name: 'Bilgisayar 7',
      price: '1200 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1200 / 3).toFixed(2) },
        { months: 6, price: (1200 / 6).toFixed(2) },
        { months: 9, price: (1200 / 9).toFixed(2) },
        { months: 12, price: (1200 / 12).toFixed(2) },
      ],
    },
    {
      id: 23,
      name: 'Bilgisayar 8',
      price: '1400 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1400 / 3).toFixed(2) },
        { months: 6, price: (1400 / 6).toFixed(2) },
        { months: 9, price: (1400 / 9).toFixed(2) },
        { months: 12, price: (1400 / 12).toFixed(2) },
      ],
    },
    {
      id: 24,
      name: 'Bilgisayar 9',
      price: '1600 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1600 / 3).toFixed(2) },
        { months: 6, price: (1600 / 6).toFixed(2) },
        { months: 9, price: (1600 / 9).toFixed(2) },
        { months: 12, price: (1600 / 12).toFixed(2) },
      ],
    },
    {
      id: 25,
      name: 'Bilgisayar 10',
      price: '1800 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1800 / 3).toFixed(2) },
        { months: 6, price: (1800 / 6).toFixed(2) },
        { months: 9, price: (1800 / 9).toFixed(2) },
        { months: 12, price: (1800 / 12).toFixed(2) },
      ],
    },
    {
      id: 26,
      name: 'Bilgisayar 11',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 27,
      name: 'Bilgisayar 12',
      price: '1200 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1200 / 3).toFixed(2) },
        { months: 6, price: (1200 / 6).toFixed(2) },
        { months: 9, price: (1200 / 9).toFixed(2) },
        { months: 12, price: (1200 / 12).toFixed(2) },
      ],
    },
    {
      id: 28,
      name: 'Bilgisayar 13',
      price: '1400 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+3',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1400 / 3).toFixed(2) },
        { months: 6, price: (1400 / 6).toFixed(2) },
        { months: 9, price: (1400 / 9).toFixed(2) },
        { months: 12, price: (1400 / 12).toFixed(2) },
      ],
    },
    {
      id: 29,
      name: 'Bilgisayar 14',
      price: '1600 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+4',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1600 / 3).toFixed(2) },
        { months: 6, price: (1600 / 6).toFixed(2) },
        { months: 9, price: (1600 / 9).toFixed(2) },
        { months: 12, price: (1600 / 12).toFixed(2) },
      ],
    },
    {
      id: 30,
      name: 'Bilgisayar 15',
      price: '1800 $',
      image: 'https://via.placeholder.com/150?text=Bilgisayar+5',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1800 / 3).toFixed(2) },
        { months: 6, price: (1800 / 6).toFixed(2) },
        { months: 9, price: (1800 / 9).toFixed(2) },
        { months: 12, price: (1800 / 12).toFixed(2) },
      ],
    },
  ],
  'Tv, Görüntü ve Ses': [
    {
      id: 31,
      name: 'TV 1',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=TV+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 32,
      name: 'TV 2',
      price: '400 $',
      image: 'https://via.placeholder.com/150?text=TV+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (400 / 3).toFixed(2) },
        { months: 6, price: (400 / 6).toFixed(2) },
        { months: 9, price: (400 / 9).toFixed(2) },
        { months: 12, price: (400 / 12).toFixed(2) },
      ],
    },
    {
      id: 33,
      name: 'Ses Sistemi 1',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 34,
      name: 'Ses Sistemi 2',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 35,
      name: 'Projeksiyon 1',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Projeksiyon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
    {
      id: 36,
      name: 'TV 6',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=TV+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 37,
      name: 'TV 7',
      price: '400 $',
      image: 'https://via.placeholder.com/150?text=TV+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (400 / 3).toFixed(2) },
        { months: 6, price: (400 / 6).toFixed(2) },
        { months: 9, price: (400 / 9).toFixed(2) },
        { months: 12, price: (400 / 12).toFixed(2) },
      ],
    },
    {
      id: 38,
      name: 'Ses Sistemi 8',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 39,
      name: 'Ses Sistemi 9',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 40,
      name: 'Projeksiyon 10',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Projeksiyon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
    {
      id: 41,
      name: 'TV 11',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=TV+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 42,
      name: 'TV 12',
      price: '400 $',
      image: 'https://via.placeholder.com/150?text=TV+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (400 / 3).toFixed(2) },
        { months: 6, price: (400 / 6).toFixed(2) },
        { months: 9, price: (400 / 9).toFixed(2) },
        { months: 12, price: (400 / 12).toFixed(2) },
      ],
    },
    {
      id: 43,
      name: 'Ses Sistemi 13',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 44,
      name: 'Ses Sistemi 14',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Ses+Sistemi+2',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 45,
      name: 'Projeksiyon 15',
      price: '700 $',
      image: 'https://via.placeholder.com/150?text=Projeksiyon+1',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (700 / 3).toFixed(2) },
        { months: 6, price: (700 / 6).toFixed(2) },
        { months: 9, price: (700 / 9).toFixed(2) },
        { months: 12, price: (700 / 12).toFixed(2) },
      ],
    },
  ],
  'Bilgisayar Parçaları': [
    {
      id: 46,
      name: 'Ekran Kartı',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ekran+Kartı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 47,
      name: 'Anakart',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=Anakart',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 48,
      name: 'RAM',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=RAM',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (150 / 3).toFixed(2) },
        { months: 6, price: (150 / 6).toFixed(2) },
        { months: 9, price: (150 / 9).toFixed(2) },
        { months: 12, price: (150 / 12).toFixed(2) },
      ],
    },
    {
      id: 49,
      name: 'SSD',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=SSD',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 50,
      name: 'İşlemci',
      price: '350 $',
      image: 'https://via.placeholder.com/150?text=İşlemci',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (350 / 3).toFixed(2) },
        { months: 6, price: (350 / 6).toFixed(2) },
        { months: 9, price: (350 / 9).toFixed(2) },
        { months: 12, price: (350 / 12).toFixed(2) },
      ],
    },
    {
      id: 51,
      name: 'Ekran Kartı 60.00',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ekran+Kartı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 52,
      name: 'Anakart 70.00',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=Anakart',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 53,
      name: 'RAM 80.00',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=RAM',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (150 / 3).toFixed(2) },
        { months: 6, price: (150 / 6).toFixed(2) },
        { months: 9, price: (150 / 9).toFixed(2) },
        { months: 12, price: (150 / 12).toFixed(2) },
      ],
    },
    {
      id: 54,
      name: 'SSD 90.00',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=SSD',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 55,
      name: 'İşlemci 10.00',
      price: '350 $',
      image: 'https://via.placeholder.com/150?text=İşlemci',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (350 / 3).toFixed(2) },
        { months: 6, price: (350 / 6).toFixed(2) },
        { months: 9, price: (350 / 9).toFixed(2) },
        { months: 12, price: (350 / 12).toFixed(2) },
      ],
    },
    {
      id: 56,
      name: 'Ekran Kartı 11.00',
      price: '500 $',
      image: 'https://via.placeholder.com/150?text=Ekran+Kartı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (500 / 3).toFixed(2) },
        { months: 6, price: (500 / 6).toFixed(2) },
        { months: 9, price: (500 / 9).toFixed(2) },
        { months: 12, price: (500 / 12).toFixed(2) },
      ],
    },
    {
      id: 57,
      name: 'Anakart 12.00',
      price: '300 $',
      image: 'https://via.placeholder.com/150?text=Anakart',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (300 / 3).toFixed(2) },
        { months: 6, price: (300 / 6).toFixed(2) },
        { months: 9, price: (300 / 9).toFixed(2) },
        { months: 12, price: (300 / 12).toFixed(2) },
      ],
    },
    {
      id: 58,
      name: 'RAM 13.00',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=RAM',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (150 / 3).toFixed(2) },
        { months: 6, price: (150 / 6).toFixed(2) },
        { months: 9, price: (150 / 9).toFixed(2) },
        { months: 12, price: (150 / 12).toFixed(2) },
      ],
    },
    {
      id: 59,
      name: 'SSD 14.00',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=SSD',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 60,
      name: 'İşlemci 15.00',
      price: '350 $',
      image: 'https://via.placeholder.com/150?text=İşlemci',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (350 / 3).toFixed(2) },
        { months: 6, price: (350 / 6).toFixed(2) },
        { months: 9, price: (350 / 9).toFixed(2) },
        { months: 12, price: (350 / 12).toFixed(2) },
      ],
    },
  ],
  'Ev & Mutfak': [
    {
      id: 61,
      name: 'Buzdolabı',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Buzdolabı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 62,
      name: 'Fırın',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Fırın',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 63,
      name: 'Mikrodalga',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=Mikrodalga',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 64,
      name: 'Bulaşık Makinesi',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Bulaşık+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 65,
      name: 'Kahve Makinesi',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=Kahve+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 66,
      name: 'Buzdolabı',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Buzdolabı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 67,
      name: 'Fırın',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Fırın',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 68,
      name: 'Mikrodalga',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=Mikrodalga',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 69,
      name: 'Bulaşık Makinesi',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Bulaşık+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 70,
      name: 'Kahve Makinesi',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=Kahve+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (150 / 3).toFixed(2) },
        { months: 6, price: (150 / 6).toFixed(2) },
        { months: 9, price: (150 / 9).toFixed(2) },
        { months: 12, price: (150 / 12).toFixed(2) },
      ],
    },
    {
      id: 71,
      name: 'Buzdolabı',
      price: '1000 $',
      image: 'https://via.placeholder.com/150?text=Buzdolabı',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (1000 / 3).toFixed(2) },
        { months: 6, price: (1000 / 6).toFixed(2) },
        { months: 9, price: (1000 / 9).toFixed(2) },
        { months: 12, price: (1000 / 12).toFixed(2) },
      ],
    },
    {
      id: 72,
      name: 'Fırın',
      price: '800 $',
      image: 'https://via.placeholder.com/150?text=Fırın',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (800 / 3).toFixed(2) },
        { months: 6, price: (800 / 6).toFixed(2) },
        { months: 9, price: (800 / 9).toFixed(2) },
        { months: 12, price: (800 / 12).toFixed(2) },
      ],
    },
    {
      id: 73,
      name: 'Mikrodalga',
      price: '200 $',
      image: 'https://via.placeholder.com/150?text=Mikrodalga',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (200 / 3).toFixed(2) },
        { months: 6, price: (200 / 6).toFixed(2) },
        { months: 9, price: (200 / 9).toFixed(2) },
        { months: 12, price: (200 / 12).toFixed(2) },
      ],
    },
    {
      id: 74,
      name: 'Bulaşık Makinesi',
      price: '600 $',
      image: 'https://via.placeholder.com/150?text=Bulaşık+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (600 / 3).toFixed(2) },
        { months: 6, price: (600 / 6).toFixed(2) },
        { months: 9, price: (600 / 9).toFixed(2) },
        { months: 12, price: (600 / 12).toFixed(2) },
      ],
    },
    {
      id: 75,
      name: 'Kahve Makinesi',
      price: '150 $',
      image: 'https://via.placeholder.com/150?text=Kahve+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (150 / 3).toFixed(2) },
        { months: 6, price: (150 / 6).toFixed(2) },
        { months: 9, price: (150 / 9).toFixed(2) },
        { months: 12, price: (150 / 12).toFixed(2) },
      ],
    },
  ],
  'Kişisel Bakım': [
    {
      id: 76,
      name: 'Saç Kurutma Makinesi',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 77,
      name: 'Tıraş Makinesi',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 78,
      name: 'Diş Fırçası',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 79,
      name: 'Epilatör',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 80,
      name: 'Masaj Aleti',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
    {
      id: 81,
      name: 'Saç Kurutma Makinesi 6',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 82,
      name: 'Tıraş Makinesi 7',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 83,
      name: 'Diş Fırçası 8',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 84,
      name: 'Epilatör 9',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 85,
      name: 'Masaj Aleti 10',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
    {
      id: 86,
      name: 'Saç Kurutma Makinesi 11',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 87,
      name: 'Tıraş Makinesi 12',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 88,
      name: 'Diş Fırçası 13',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 89,
      name: 'Epilatör 14',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 90,
      name: 'Masaj Aleti 15',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
  ],
  OEM: [
    {
      id: 91,
      name: 'OEM 1',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 92,
      name: 'OEM 2',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 93,
      name: 'OEM 3',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 94,
      name: 'OEM 4',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 95,
      name: 'OEM 5',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
    {
      id: 96,
      name: 'OEM 6',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 97,
      name: 'OEM 7',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 98,
      name: 'OEM 8',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 99,
      name: 'OEM 9',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 100,
      name: 'OEM 10',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
    {
      id: 101,
      name: 'OEM 11',
      price: '50 $',
      image: 'https://via.placeholder.com/150?text=Saç+Kurutma+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (50 / 3).toFixed(2) },
        { months: 6, price: (50 / 6).toFixed(2) },
        { months: 9, price: (50 / 9).toFixed(2) },
        { months: 12, price: (50 / 12).toFixed(2) },
      ],
    },
    {
      id: 102,
      name: 'OEM 12',
      price: '40 $',
      image: 'https://via.placeholder.com/150?text=Tıraş+Makinesi',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (40 / 3).toFixed(2) },
        { months: 6, price: (40 / 6).toFixed(2) },
        { months: 9, price: (40 / 9).toFixed(2) },
        { months: 12, price: (40 / 12).toFixed(2) },
      ],
    },
    {
      id: 103,
      name: 'OEM 13',
      price: '30 $',
      image: 'https://via.placeholder.com/150?text=Diş+Fırçası',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (30 / 3).toFixed(2) },
        { months: 6, price: (30 / 6).toFixed(2) },
        { months: 9, price: (30 / 9).toFixed(2) },
        { months: 12, price: (30 / 12).toFixed(2) },
      ],
    },
    {
      id: 104,
      name: 'OEM 14',
      price: '60 $',
      image: 'https://via.placeholder.com/150?text=Epilatör',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (60 / 3).toFixed(2) },
        { months: 6, price: (60 / 6).toFixed(2) },
        { months: 9, price: (60 / 9).toFixed(2) },
        { months: 12, price: (60 / 12).toFixed(2) },
      ],
    },
    {
      id: 105,
      name: 'OEM 15',
      price: '100 $',
      image: 'https://via.placeholder.com/150?text=Masaj+Aleti',
      description: [
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
        'lorem ipsum dolor sit amet',
      ],
      installmentOptions: [
        { months: 3, price: (100 / 3).toFixed(2) },
        { months: 6, price: (100 / 6).toFixed(2) },
        { months: 9, price: (100 / 9).toFixed(2) },
        { months: 12, price: (100 / 12).toFixed(2) },
      ],
    },
  ],
};

const Home = ({ addToCart }) => {
  const categories = Object.keys(productData);
  const [activeCategory, setActiveCategory] = useState(categories[0]);

  const handleCategoryClick = (category) => {
    setActiveCategory(category);
  };

  return (
    <div className="p-8">
      {/* Kategoriler Butonları */}
      <div className="flex flex-wrap justify-center gap-4 mb-8">
        {categories.map((category) => (
          <button
            key={category}
            className={`px-4 py-2 rounded-lg transition-all duration-300 ease-in-out transform hover:bg-blue-600 hover:text-white border border-blue-500 ${
              activeCategory === category
                ? 'bg-blue-500 text-white'
                : 'bg-gray-200 text-gray-700'
            }`}
            onClick={() => handleCategoryClick(category)}
          >
            {category}
          </button>
        ))}
      </div>

      {/* Ürün Kartları */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 select-none text-blue-600 cursor-pointer">
        {productData[activeCategory].map((product) => (
          <Link
            to={`/${activeCategory}/${product.id}`}
            key={product.id}
            className="block"
          >
            <div className="border p-4 rounded shadow-md bg-white hover:shadow-lg transition-transform transform hover:scale-105">
              <img
                src={product.image}
                alt={product.name}
                className="w-full h-32 object-cover mb-4"
              />
              <h2 className="text-lg font-semibold mb-2">{product.name}</h2>
              <p className="text-gray-500">{product.description}</p>
              <p className="text-black font-bold">{product.price}</p>
              <div className="flex justify-between">
                <button className="mt-4 bg-blue-600 text-white py-2 px-4 rounded hover:bg-blue-700">
                  Detaylar
                </button>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Home;
